"""Prompt registry service.

Everything that enforces the registry's guarantees lives here: monotonic version
numbering, immutability, and atomic label promotion. The API layer is a thin
translation of HTTP to these calls, so the worker and the eval runner get the
same guarantees for free.
"""

from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy import Select, func, select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from lo_core import templating
from lo_core.db.models.prompt import Prompt, PromptLabel, PromptVersion
from lo_core.diffing import diff_versions
from lo_core.errors import ConflictError, NotFoundError
from lo_core.schemas.prompt import (
    LabelAssign,
    Message,
    PromptCreate,
    PromptDiff,
    PromptLabelRead,
    PromptRead,
    PromptUpdate,
    PromptVersionCreate,
    RenderResponse,
)


def _messages_from_row(raw: list[dict[str, Any]]) -> list[Message]:
    return [Message.model_validate(m) for m in raw]


# --- Prompts --------------------------------------------------------------


async def create_prompt(
    session: AsyncSession,
    project_id: uuid.UUID,
    payload: PromptCreate,
) -> Prompt:
    prompt = Prompt(
        project_id=project_id,
        slug=payload.slug,
        name=payload.name,
        description=payload.description,
    )
    session.add(prompt)
    try:
        await session.flush()
    except IntegrityError as exc:
        raise ConflictError(f"prompt slug {payload.slug!r} already exists in this project") from exc
    return prompt


async def get_prompt(session: AsyncSession, project_id: uuid.UUID, slug: str) -> Prompt:
    """Fetch by slug, always scoped to a project.

    The `project_id` predicate is not optional and not a convenience. It is the
    tenancy check: without it, knowing a slug in another project would be enough
    to read it. Every lookup in this module carries the same scoping.
    """
    result = await session.execute(
        select(Prompt).where(Prompt.project_id == project_id, Prompt.slug == slug)
    )
    prompt = result.scalar_one_or_none()
    if prompt is None:
        raise NotFoundError(f"prompt {slug!r} not found")
    return prompt


async def update_prompt(session: AsyncSession, prompt: Prompt, payload: PromptUpdate) -> Prompt:
    """Update descriptive metadata only. Content changes create a new version."""
    if payload.name is not None:
        prompt.name = payload.name
    if payload.description is not None:
        prompt.description = payload.description
    await session.flush()

    # `updated_at` is generated by the server via `onupdate`, so after the UPDATE
    # SQLAlchemy marks it expired and would refetch it on next access. Under
    # asyncio that implicit refetch is illegal — attribute access is synchronous
    # and cannot await IO, producing `MissingGreenlet` at whatever point the
    # value is eventually read (serialisation, typically, far from the cause).
    # Refreshing explicitly keeps the IO where it can be awaited.
    await session.refresh(prompt)
    return prompt


async def delete_prompt(session: AsyncSession, prompt: Prompt) -> None:
    """Delete a prompt and, by cascade, its versions and labels.

    The label -> version foreign key is RESTRICT, but that does not block this:
    Postgres applies the prompt's CASCADE to `prompt_labels` and
    `prompt_versions` within one statement, so the labels are gone before their
    versions are removed.
    """
    await session.delete(prompt)
    await session.flush()


# --- Versions -------------------------------------------------------------


async def create_version(
    session: AsyncSession,
    prompt: Prompt,
    payload: PromptVersionCreate,
) -> PromptVersion:
    """Append an immutable version, numbered one above the current maximum.

    **Concurrency.** `max(version) + 1` is a read-then-write, and two concurrent
    requests would otherwise both read 3 and both try to write 4. The unique
    constraint on `(prompt_id, version)` would catch that, but as a 500-level
    integrity error on a legitimate request.

    Instead the prompt row is locked with `SELECT ... FOR UPDATE` first, so
    concurrent writers to the *same* prompt serialise and each gets a distinct
    number. Writers to different prompts never contend, because the lock is on
    that prompt's row rather than on the table. The unique constraint stays as
    the backstop that guarantees correctness even if this logic is ever bypassed.
    """
    # Validate and analyse the templates before taking the lock — no reason to
    # hold a row lock while parsing, and a syntax error should not depend on
    # winning a race first.
    for message in payload.messages:
        templating.compile_template(message.content)

    variables = templating.extract_variables(m.content for m in payload.messages)
    parameters = payload.parameters.model_dump(exclude_none=True)
    digest = templating.content_hash(payload.messages, parameters)

    await session.execute(select(Prompt.id).where(Prompt.id == prompt.id).with_for_update())

    current_max = await session.scalar(
        select(func.max(PromptVersion.version)).where(PromptVersion.prompt_id == prompt.id)
    )
    next_version = (current_max or 0) + 1

    version = PromptVersion(
        prompt_id=prompt.id,
        version=next_version,
        messages=[m.model_dump() for m in payload.messages],
        variables=[v.model_dump() for v in variables],
        parameters=parameters,
        content_hash=digest,
        commit_sha=payload.commit_sha,
        created_by=payload.created_by,
        change_note=payload.change_note,
    )
    session.add(version)
    try:
        await session.flush()
    except IntegrityError as exc:  # pragma: no cover - the row lock prevents this
        raise ConflictError("concurrent version creation; retry the request") from exc
    return version


async def get_version(session: AsyncSession, prompt_id: uuid.UUID, version: int) -> PromptVersion:
    result = await session.execute(
        select(PromptVersion).where(
            PromptVersion.prompt_id == prompt_id, PromptVersion.version == version
        )
    )
    found = result.scalar_one_or_none()
    if found is None:
        raise NotFoundError(f"version {version} not found")
    return found


async def list_versions(
    session: AsyncSession,
    prompt_id: uuid.UUID,
    limit: int = 50,
    offset: int = 0,
) -> list[PromptVersion]:
    result = await session.execute(
        select(PromptVersion)
        .where(PromptVersion.prompt_id == prompt_id)
        .order_by(PromptVersion.version.desc())
        .limit(limit)
        .offset(offset)
    )
    return list(result.scalars().all())


async def resolve_version(
    session: AsyncSession,
    prompt_id: uuid.UUID,
    ref: str,
) -> PromptVersion:
    """Resolve a version reference that may be a number or a label.

    Callers reference prompts as `support-triage@production` or
    `support-triage@7`. Accepting both in one resolver is what lets an
    application pin to `production` while CI pins to an exact number, using the
    same API path.
    """
    if ref.isdigit():
        return await get_version(session, prompt_id, int(ref))

    result = await session.execute(
        select(PromptVersion)
        .join(PromptLabel, PromptLabel.version_id == PromptVersion.id)
        .where(PromptLabel.prompt_id == prompt_id, PromptLabel.label == ref)
    )
    found = result.scalar_one_or_none()
    if found is None:
        raise NotFoundError(f"no version labelled {ref!r}")
    return found


# --- Labels ---------------------------------------------------------------


async def assign_label(
    session: AsyncSession,
    prompt: Prompt,
    label: str,
    payload: LabelAssign,
) -> PromptLabel:
    """Point `label` at a version, atomically.

    Implemented as a single `INSERT ... ON CONFLICT (prompt_id, label) DO UPDATE`
    rather than a read-then-write. A delete-then-insert would leave a window in
    which no version is labelled "production"; a select-then-update would race
    with a concurrent promotion. The upsert is one statement, so readers see
    either the old target or the new one and never an absence.
    """
    version = await get_version(session, prompt.id, payload.version)

    stmt = (
        pg_insert(PromptLabel)
        .values(
            id=uuid.uuid4(),
            prompt_id=prompt.id,
            label=label,
            version_id=version.id,
            updated_by=payload.updated_by,
        )
        .on_conflict_do_update(
            index_elements=[PromptLabel.prompt_id, PromptLabel.label],
            set_={
                "version_id": version.id,
                "updated_by": payload.updated_by,
                "updated_at": func.now(),
            },
        )
        .returning(PromptLabel)
    )
    result = await session.execute(stmt)
    await session.flush()
    return result.scalar_one()


async def list_labels(session: AsyncSession, prompt_id: uuid.UUID) -> list[PromptLabelRead]:
    result = await session.execute(
        select(PromptLabel, PromptVersion.version)
        .join(PromptVersion, PromptVersion.id == PromptLabel.version_id)
        .where(PromptLabel.prompt_id == prompt_id)
        .order_by(PromptLabel.label)
    )
    return [
        PromptLabelRead(
            label=row.PromptLabel.label,
            version_id=row.PromptLabel.version_id,
            version=row.version,
            updated_by=row.PromptLabel.updated_by,
            updated_at=row.PromptLabel.updated_at,
        )
        for row in result
    ]


async def remove_label(session: AsyncSession, prompt_id: uuid.UUID, label: str) -> None:
    result = await session.execute(
        select(PromptLabel).where(PromptLabel.prompt_id == prompt_id, PromptLabel.label == label)
    )
    found = result.scalar_one_or_none()
    if found is None:
        raise NotFoundError(f"label {label!r} not found")
    await session.delete(found)
    await session.flush()


# --- Reads, rendering and diffs ------------------------------------------


def _prompts_query(project_id: uuid.UUID) -> Select[tuple[Prompt]]:
    return select(Prompt).where(Prompt.project_id == project_id).order_by(Prompt.slug)


async def list_prompt_reads(
    session: AsyncSession,
    project_id: uuid.UUID,
    limit: int = 100,
    offset: int = 0,
) -> list[PromptRead]:
    """List prompts with their latest version number and current labels.

    Deliberately three queries with no per-row lookups. The obvious
    implementation — fetch prompts, then load `.versions` and `.labels` per
    prompt — is an N+1 that looks fine against ten prompts in development and
    falls over against a real registry. The relationships are declared
    `lazy="raise"` precisely so that mistake fails loudly instead of silently
    working.
    """
    result = await session.execute(_prompts_query(project_id).limit(limit).offset(offset))
    prompts = list(result.scalars().all())
    if not prompts:
        return []

    prompt_ids = [p.id for p in prompts]

    latest_result = await session.execute(
        select(PromptVersion.prompt_id, func.max(PromptVersion.version))
        .where(PromptVersion.prompt_id.in_(prompt_ids))
        .group_by(PromptVersion.prompt_id)
    )
    latest: dict[uuid.UUID, int] = dict(latest_result.all())  # type: ignore[arg-type]

    labels_result = await session.execute(
        select(PromptLabel, PromptVersion.version)
        .join(PromptVersion, PromptVersion.id == PromptLabel.version_id)
        .where(PromptLabel.prompt_id.in_(prompt_ids))
        .order_by(PromptLabel.label)
    )
    labels_by_prompt: dict[uuid.UUID, list[PromptLabelRead]] = {}
    for row in labels_result:
        labels_by_prompt.setdefault(row.PromptLabel.prompt_id, []).append(
            PromptLabelRead(
                label=row.PromptLabel.label,
                version_id=row.PromptLabel.version_id,
                version=row.version,
                updated_by=row.PromptLabel.updated_by,
                updated_at=row.PromptLabel.updated_at,
            )
        )

    return [
        PromptRead(
            id=p.id,
            project_id=p.project_id,
            slug=p.slug,
            name=p.name,
            description=p.description,
            created_at=p.created_at,
            updated_at=p.updated_at,
            latest_version=latest.get(p.id),
            labels=labels_by_prompt.get(p.id, []),
        )
        for p in prompts
    ]


async def build_prompt_read(session: AsyncSession, prompt: Prompt) -> PromptRead:
    latest = await session.scalar(
        select(func.max(PromptVersion.version)).where(PromptVersion.prompt_id == prompt.id)
    )
    return PromptRead(
        id=prompt.id,
        project_id=prompt.project_id,
        slug=prompt.slug,
        name=prompt.name,
        description=prompt.description,
        created_at=prompt.created_at,
        updated_at=prompt.updated_at,
        latest_version=latest,
        labels=await list_labels(session, prompt.id),
    )


async def render_version(
    session: AsyncSession,
    prompt_id: uuid.UUID,
    ref: str,
    variables: dict[str, Any],
) -> RenderResponse:
    version = await resolve_version(session, prompt_id, ref)
    messages = _messages_from_row(version.messages)
    return RenderResponse(
        version=version.version,
        messages=templating.render_messages(messages, variables),
        parameters=version.parameters,
    )


async def diff_prompt_versions(
    session: AsyncSession,
    prompt_id: uuid.UUID,
    from_ref: str,
    to_ref: str,
) -> PromptDiff:
    """Diff two versions, each addressable by number or label.

    Accepting labels here is what makes the useful question cheap to ask:
    "what changed between what is in production and what I am about to ship?"
    is `?from=production&to=staging`, with no need to look up numbers first.
    """
    before = await resolve_version(session, prompt_id, from_ref)
    after = await resolve_version(session, prompt_id, to_ref)

    return diff_versions(
        prompt_id=prompt_id,
        from_version=before.version,
        from_messages=_messages_from_row(before.messages),
        from_parameters=before.parameters,
        to_version=after.version,
        to_messages=_messages_from_row(after.messages),
        to_parameters=after.parameters,
    )
