"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Created: ${create_date}

Review checklist before merging an autogenerated migration:
  - Is `downgrade()` actually correct, or did autogenerate guess?
  - Does any index on a large table need `postgresql_concurrently=True`
    (which also requires this revision to run outside a transaction)?
  - Does a new NOT NULL column on an existing table have a server_default,
    or will it lock and fail against real data?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}
revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
