"""Column mixins shared by every mapped class.

Timestamps default on the *server* rather than in Python. A client-side default
records the application pod's clock, which drifts between nodes and makes
"created_at" ordering unreliable across replicas; `now()` is evaluated by
Postgres, so every row in the cluster is stamped by one clock.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKey:
    """A UUID primary key generated by the application.

    Chosen over a bigserial because IDs appear in URLs and in API payloads that
    cross a tenancy boundary: sequential integers leak row counts and invite
    enumeration of other projects' resources.

    The tradeoff is index locality — random uuid4 values scatter B-tree inserts
    instead of appending to the rightmost leaf. That is acceptable for these
    low-volume control-plane tables. The high-volume telemetry tables should not
    copy this pattern; see docs/adr/0003-trace-storage.md.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """`created_at` / `updated_at`, both server-generated and timezone-aware.

    `DateTime(timezone=True)` maps to `timestamptz`. Plain `timestamp` stores no
    offset, so the same value means different instants depending on the reader's
    session timezone — which turns latency and cost aggregations into quiet
    nonsense the moment anything runs outside UTC.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class CreatedAtMixin:
    """`created_at` only — for append-only tables.

    Immutable rows (prompt versions, traces, eval results) deliberately have no
    `updated_at`. Its absence is the schema stating that these rows are never
    mutated, which is what lets other tables reference them as a stable record of
    what actually ran.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
