"""guardrail sampling and review queue

Revision ID: eb1a50ddb127
Revises: 6ba29a171a6a
Created: 2026-08-17 15:58:32.572977+00:00

Review checklist before merging an autogenerated migration:
  - Is `downgrade()` actually correct, or did autogenerate guess?
  - Does any index on a large table need `postgresql_concurrently=True`
    (which also requires this revision to run outside a transaction)?
  - Does a new NOT NULL column on an existing table have a server_default,
    or will it lock and fail against real data?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "eb1a50ddb127"
down_revision: str | None = "6ba29a171a6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guardrail_configs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sample_rate", sa.Float(), server_default="0.1", nullable=False),
        sa.Column("control_sample_rate", sa.Float(), server_default="0.05", nullable=False),
        sa.Column("check_pii", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("check_grounding", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("check_toxicity", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("context_field", sa.String(length=64), server_default="context", nullable=False),
        sa.Column("escalate_to_judge", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("judge_rubric", sa.String(length=64), nullable=True),
        sa.Column("judge_model", sa.String(length=100), nullable=True),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "control_sample_rate >= 0 AND control_sample_rate <= 1",
            name=op.f("ck_guardrail_configs_control_sample_rate_range"),
        ),
        sa.CheckConstraint(
            "sample_rate >= 0 AND sample_rate <= 1",
            name=op.f("ck_guardrail_configs_sample_rate_range"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["control.projects.id"],
            name=op.f("fk_guardrail_configs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guardrail_configs")),
        sa.UniqueConstraint("project_id", name="uq_guardrail_configs_project_id"),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_guardrail_configs_project_id"),
        "guardrail_configs",
        ["project_id"],
        unique=False,
        schema="control",
    )
    op.create_table(
        "review_items",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("sampled_as", sa.String(length=16), server_default="flagged", nullable=False),
        sa.Column(
            "findings", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("severity", sa.Float(), server_default="0", nullable=False),
        sa.Column("trace_name", sa.String(length=200), server_default="", nullable=False),
        sa.Column(
            "inputs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("verdict", sa.String(length=16), nullable=True),
        sa.Column("label_reason", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("corrected_output", sa.Text(), nullable=True),
        sa.Column("labeled_by", sa.String(length=200), nullable=True),
        sa.Column("labeled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_to_version_id", sa.Uuid(), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sampled_as IN ('flagged', 'control')", name=op.f("ck_review_items_sampled_as_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'labeled', 'skipped')", name=op.f("ck_review_items_status_valid")
        ),
        sa.CheckConstraint(
            "verdict IS NULL OR verdict IN ('good', 'bad')",
            name=op.f("ck_review_items_verdict_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["control.projects.id"],
            name=op.f("fk_review_items_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["promoted_to_version_id"],
            ["control.dataset_versions.id"],
            name=op.f("fk_review_items_promoted_to_version_id_dataset_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_items")),
        sa.UniqueConstraint("project_id", "trace_id", name="uq_review_items_project_id_trace_id"),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_review_items_project_id"),
        "review_items",
        ["project_id"],
        unique=False,
        schema="control",
    )
    op.create_index(
        op.f("ix_control_review_items_promoted_to_version_id"),
        "review_items",
        ["promoted_to_version_id"],
        unique=False,
        schema="control",
    )
    op.create_index(
        op.f("ix_control_review_items_trace_id"),
        "review_items",
        ["trace_id"],
        unique=False,
        schema="control",
    )
    op.create_index(
        "ix_review_items_project_id_status_severity",
        "review_items",
        ["project_id", "status", "severity"],
        unique=False,
        schema="control",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_review_items_project_id_status_severity", table_name="review_items", schema="control"
    )
    op.drop_index(
        op.f("ix_control_review_items_trace_id"), table_name="review_items", schema="control"
    )
    op.drop_index(
        op.f("ix_control_review_items_promoted_to_version_id"),
        table_name="review_items",
        schema="control",
    )
    op.drop_index(
        op.f("ix_control_review_items_project_id"), table_name="review_items", schema="control"
    )
    op.drop_table("review_items", schema="control")
    op.drop_index(
        op.f("ix_control_guardrail_configs_project_id"),
        table_name="guardrail_configs",
        schema="control",
    )
    op.drop_table("guardrail_configs", schema="control")
    # ### end Alembic commands ###
