"""judge prompts and run judge link

Revision ID: f7c7a402c376
Revises: 88d83f8db27e
Created: 2026-08-12 10:04:39.428056+00:00

Review checklist before merging an autogenerated migration:
  - Is `downgrade()` actually correct, or did autogenerate guess?
  - Does any index on a large table need `postgresql_concurrently=True`
    (which also requires this revision to run outside a transaction)?
  - Does a new NOT NULL column on an existing table have a server_default,
    or will it lock and fail against real data?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f7c7a402c376"
down_revision: str | None = "88d83f8db27e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eval_runs",
        sa.Column("judge_prompt_version_id", sa.Uuid(), nullable=True),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_eval_runs_judge_prompt_version_id"),
        "eval_runs",
        ["judge_prompt_version_id"],
        unique=False,
        schema="control",
    )
    op.create_foreign_key(
        op.f("fk_eval_runs_judge_prompt_version_id_prompt_versions"),
        "eval_runs",
        "prompt_versions",
        ["judge_prompt_version_id"],
        ["id"],
        source_schema="control",
        referent_schema="control",
        ondelete="RESTRICT",
    )
    op.add_column(
        "prompts",
        sa.Column("kind", sa.String(length=16), server_default="application", nullable=False),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_prompts_kind"), "prompts", ["kind"], unique=False, schema="control"
    )
    op.create_check_constraint(
        op.f("ck_prompts_kind_valid"),
        "prompts",
        "kind IN ('application', 'judge')",
        schema="control",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_prompts_kind_valid"), "prompts", schema="control", type_="check")
    op.drop_index(op.f("ix_control_prompts_kind"), table_name="prompts", schema="control")
    op.drop_column("prompts", "kind", schema="control")
    op.drop_constraint(
        op.f("fk_eval_runs_judge_prompt_version_id_prompt_versions"),
        "eval_runs",
        schema="control",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_control_eval_runs_judge_prompt_version_id"),
        table_name="eval_runs",
        schema="control",
    )
    op.drop_column("eval_runs", "judge_prompt_version_id", schema="control")
    # ### end Alembic commands ###
