"""alert rules

Revision ID: 6ba29a171a6a
Revises: 67465157137f
Created: 2026-08-17 12:03:00.668164+00:00

Review checklist before merging an autogenerated migration:
  - Is `downgrade()` actually correct, or did autogenerate guess?
  - Does any index on a large table need `postgresql_concurrently=True`
    (which also requires this revision to run outside a transaction)?
  - Does a new NOT NULL column on an existing table have a server_default,
    or will it lock and fail against real data?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6ba29a171a6a"
down_revision: str | None = "67465157137f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metric", sa.String(length=32), nullable=False),
        sa.Column("comparison", sa.String(length=8), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("window_seconds", sa.Integer(), server_default="300", nullable=False),
        sa.Column("min_sample_size", sa.Integer(), server_default="5", nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), server_default="900", nullable=False),
        sa.Column("webhook_url", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_value", sa.Float(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "comparison IN ('above', 'below')", name=op.f("ck_alert_rules_comparison_valid")
        ),
        sa.CheckConstraint(
            "metric IN ('error_rate', 'p95_latency_ms', 'p99_latency_ms', 'cost_usd', 'trace_count')",
            name=op.f("ck_alert_rules_metric_valid"),
        ),
        sa.CheckConstraint(
            "cooldown_seconds >= 0", name=op.f("ck_alert_rules_cooldown_non_negative")
        ),
        sa.CheckConstraint("window_seconds > 0", name=op.f("ck_alert_rules_window_positive")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["control.projects.id"],
            name=op.f("fk_alert_rules_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
        sa.UniqueConstraint("project_id", "name", name="uq_alert_rules_project_id_name"),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_alert_rules_project_id"),
        "alert_rules",
        ["project_id"],
        unique=False,
        schema="control",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_control_alert_rules_project_id"), table_name="alert_rules", schema="control"
    )
    op.drop_table("alert_rules", schema="control")
    # ### end Alembic commands ###
