"""prompt registry

Revision ID: bc10faa914b9
Revises:
Created: 2026-08-11 22:27:26.328281+00:00

Review checklist before merging an autogenerated migration:
  - Is `downgrade()` actually correct, or did autogenerate guess?
  - Does any index on a large table need `postgresql_concurrently=True`
    (which also requires this revision to run outside a transaction)?
  - Does a new NOT NULL column on an existing table have a server_default,
    or will it lock and fail against real data?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bc10faa914b9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_projects_slug"), "projects", ["slug"], unique=True, schema="control"
    )
    op.create_table(
        "prompts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9_-]{0,63}$'", name=op.f("ck_prompts_slug_format")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["control.projects.id"],
            name=op.f("fk_prompts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompts")),
        sa.UniqueConstraint("project_id", "slug", name="uq_prompts_project_id_slug"),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_prompts_project_id"),
        "prompts",
        ["project_id"],
        unique=False,
        schema="control",
    )
    op.create_table(
        "prompt_versions",
        sa.Column("prompt_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("messages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "variables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=True),
        sa.Column("change_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_prompt_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["control.prompts.id"],
            name=op.f("fk_prompt_versions_prompt_id_prompts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("prompt_id", "version", name="uq_prompt_versions_prompt_id_version"),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_prompt_versions_prompt_id"),
        "prompt_versions",
        ["prompt_id"],
        unique=False,
        schema="control",
    )
    op.create_index(
        "ix_prompt_versions_prompt_id_content_hash",
        "prompt_versions",
        ["prompt_id", "content_hash"],
        unique=False,
        schema="control",
    )
    op.create_table(
        "prompt_labels",
        sa.Column("prompt_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "label ~ '^[a-z0-9][a-z0-9_-]{0,31}$'", name=op.f("ck_prompt_labels_label_format")
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["control.prompts.id"],
            name=op.f("fk_prompt_labels_prompt_id_prompts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["control.prompt_versions.id"],
            name=op.f("fk_prompt_labels_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_labels")),
        sa.UniqueConstraint("prompt_id", "label", name="uq_prompt_labels_prompt_id_label"),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_prompt_labels_prompt_id"),
        "prompt_labels",
        ["prompt_id"],
        unique=False,
        schema="control",
    )
    op.create_index(
        op.f("ix_control_prompt_labels_version_id"),
        "prompt_labels",
        ["version_id"],
        unique=False,
        schema="control",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_control_prompt_labels_version_id"), table_name="prompt_labels", schema="control"
    )
    op.drop_index(
        op.f("ix_control_prompt_labels_prompt_id"), table_name="prompt_labels", schema="control"
    )
    op.drop_table("prompt_labels", schema="control")
    op.drop_index(
        "ix_prompt_versions_prompt_id_content_hash", table_name="prompt_versions", schema="control"
    )
    op.drop_index(
        op.f("ix_control_prompt_versions_prompt_id"), table_name="prompt_versions", schema="control"
    )
    op.drop_table("prompt_versions", schema="control")
    op.drop_index(op.f("ix_control_prompts_project_id"), table_name="prompts", schema="control")
    op.drop_table("prompts", schema="control")
    op.drop_index(op.f("ix_control_projects_slug"), table_name="projects", schema="control")
    op.drop_table("projects", schema="control")
    # ### end Alembic commands ###
