"""api keys and telemetry spans

Revision ID: 67465157137f
Revises: f7c7a402c376
Created: 2026-08-12 17:13:31.709445+00:00

Review checklist before merging an autogenerated migration:
  - Is `downgrade()` actually correct, or did autogenerate guess?
  - Does any index on a large table need `postgresql_concurrently=True`
    (which also requires this revision to run outside a transaction)?
  - Does a new NOT NULL column on an existing table have a server_default,
    or will it lock and fail against real data?
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "67465157137f"
down_revision: str | None = "f7c7a402c376"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spans",
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("parent_span_id", sa.String(length=16), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), server_default="other", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ok", nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("span_input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("span_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "span_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("error_type", sa.String(length=200), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('chain', 'llm', 'retrieval', 'rerank', 'tool', 'embedding', 'guardrail', 'other')",
            name=op.f("ck_spans_kind_valid"),
        ),
        sa.CheckConstraint("status IN ('ok', 'error')", name=op.f("ck_spans_status_valid")),
        sa.CheckConstraint("duration_ms >= 0", name=op.f("ck_spans_duration_non_negative")),
        sa.PrimaryKeyConstraint("started_at", "span_id", name="pk_spans"),
        schema="telemetry",
    )
    op.create_index(
        "ix_spans_project_id_kind_started_at",
        "spans",
        ["project_id", "kind", "started_at"],
        unique=False,
        schema="telemetry",
    )
    op.create_index(
        "ix_spans_project_id_started_at",
        "spans",
        ["project_id", "started_at"],
        unique=False,
        schema="telemetry",
    )
    op.create_index(
        "ix_spans_trace_id_started_at",
        "spans",
        ["trace_id", "started_at"],
        unique=False,
        schema="telemetry",
    )
    op.create_table(
        "traces",
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ok", nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("span_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_prompt_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_completion_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column(
            "trace_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("flagged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ok', 'error')", name=op.f("ck_traces_status_valid")),
        sa.PrimaryKeyConstraint("started_at", "trace_id", name="pk_traces"),
        schema="telemetry",
    )
    op.create_index(
        "ix_traces_project_id_started_at",
        "traces",
        ["project_id", "started_at"],
        unique=False,
        schema="telemetry",
    )
    op.create_index(
        "ix_traces_project_id_status_started_at",
        "traces",
        ["project_id", "status", "started_at"],
        unique=False,
        schema="telemetry",
    )
    op.create_table(
        "api_keys",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("key_prefix", sa.String(length=32), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='["ingest"]',
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["control.projects.id"],
            name=op.f("fk_api_keys_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        schema="control",
    )
    op.create_index(
        op.f("ix_control_api_keys_key_prefix"),
        "api_keys",
        ["key_prefix"],
        unique=False,
        schema="control",
    )
    op.create_index(
        op.f("ix_control_api_keys_project_id"),
        "api_keys",
        ["project_id"],
        unique=False,
        schema="control",
    )
    # ### end Alembic commands ###

    # --- TimescaleDB -------------------------------------------------------
    #
    # Autogenerate cannot produce these: it compares SQLAlchemy metadata against
    # the catalogue and knows nothing about hypertables, so the conversion is
    # hand-written and must be maintained here.
    #
    # `create_hypertable` turns an ordinary table into a partitioned one. It
    # requires the table to be empty, which is why it runs in the same migration
    # that creates it rather than being retrofitted later.
    #
    # One-day chunks suit the access pattern: dashboard queries are bounded to
    # recent windows and skip every chunk outside them, while a day is coarse
    # enough that a month of data is ~30 chunks rather than thousands.
    op.execute(
        "SELECT create_hypertable('telemetry.spans', 'started_at', "
        "chunk_time_interval => INTERVAL '1 day')"
    )
    op.execute(
        "SELECT create_hypertable('telemetry.traces', 'started_at', "
        "chunk_time_interval => INTERVAL '1 day')"
    )

    # Retention and compression are deliberately NOT set here. Both are policy
    # decisions that differ per environment — a development database wants
    # neither, and production retention is a compliance question rather than an
    # engineering one. They are applied as operational settings, e.g.:
    #
    #   SELECT add_retention_policy('telemetry.spans', INTERVAL '90 days');
    #   ALTER TABLE telemetry.spans SET (timescaledb.compress,
    #       timescaledb.compress_segmentby = 'project_id');
    #   SELECT add_compression_policy('telemetry.spans', INTERVAL '7 days');
    #
    # Encoding a 90-day retention in a migration would silently delete a
    # customer's data on deploy.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_control_api_keys_project_id"), table_name="api_keys", schema="control")
    op.drop_index(op.f("ix_control_api_keys_key_prefix"), table_name="api_keys", schema="control")
    op.drop_table("api_keys", schema="control")
    op.drop_index("ix_traces_project_id_status_started_at", table_name="traces", schema="telemetry")
    op.drop_index("ix_traces_project_id_started_at", table_name="traces", schema="telemetry")
    op.drop_table("traces", schema="telemetry")
    op.drop_index("ix_spans_trace_id_started_at", table_name="spans", schema="telemetry")
    op.drop_index("ix_spans_project_id_started_at", table_name="spans", schema="telemetry")
    op.drop_index("ix_spans_project_id_kind_started_at", table_name="spans", schema="telemetry")
    op.drop_table("spans", schema="telemetry")
    # ### end Alembic commands ###
