"""Property-based tests for span-tree assembly.

`tests/integration/test_traces_api.py` covers this by example: a specific tree,
a specific arrival order, a specific orphan. Examples prove that the cases
someone thought of work. These generate the cases nobody thought of.

The distinction matters here more than in most places, because span ids and
parent pointers are **client-supplied**. W3C Trace Context ids are generated by
the instrumented application, so the shapes reaching `build_tree` are bounded by
what a buggy or hostile SDK can emit, not by what our own SDK does. Anything
this function can be handed, it will eventually be handed.

The properties below are deliberately about *invariants* rather than outputs:
"no span is lost" holds for every input, whereas "this tree looks like that" has
to be restated for each example.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta

import pytest
from hypothesis import HealthCheck, assume, given, settings
from hypothesis import strategies as st

from lo_core.db.models.telemetry import Span
from lo_core.schemas.telemetry import SpanNode
from lo_core.services.traces import MAX_TREE_DEPTH, build_tree

# Deadlines off: these build and walk trees of up to a few hundred nodes, and a
# per-example wall-clock limit turns that into flakiness on a loaded machine
# rather than into signal.
COMMON = settings(deadline=None, suppress_health_check=[HealthCheck.too_slow])

PROJECT_ID = uuid.uuid4()
TRACE_ID = "a" * 32
BASE_TIME = datetime(2026, 8, 22, 12, 0, tzinfo=UTC)


def make_span(span_id: str, parent_span_id: str | None, offset: int = 0) -> Span:
    return Span(
        started_at=BASE_TIME + timedelta(milliseconds=offset),
        span_id=span_id,
        trace_id=TRACE_ID,
        parent_span_id=parent_span_id,
        project_id=PROJECT_ID,
        name=f"span-{span_id[:6]}",
        kind="other",
        status="ok",
        span_metadata={},
    )


def span_id(index: int) -> str:
    """A valid 16-hex-character span id, derived from an index."""
    return f"{index:016x}"


@st.composite
def span_graphs(draw: st.DrawFn, max_spans: int = 25) -> list[Span]:
    """Arbitrary parent pointers — the shape a hostile client can produce.

    Parents are drawn from *any* span id including the span's own, plus ids that
    are absent from the set. That deliberately generates self-parents, cycles,
    forests, orphans and multiple roots, because nothing stops a client emitting
    any of them.
    """
    count = draw(st.integers(min_value=1, max_value=max_spans))
    ids = [span_id(i) for i in range(count)]
    absent = [span_id(1000 + i) for i in range(3)]

    spans = []
    for i, sid in enumerate(ids):
        parent = draw(
            st.one_of(
                st.none(),
                st.sampled_from(ids),  # includes itself, and later spans
                st.sampled_from(absent),
            )
        )
        spans.append(make_span(sid, parent, offset=i))
    return spans


@st.composite
def well_formed_trees(draw: st.DrawFn, max_spans: int = 30) -> list[Span]:
    """A genuine tree: every parent precedes its child, exactly one root."""
    count = draw(st.integers(min_value=1, max_value=max_spans))
    spans = [make_span(span_id(0), None, offset=0)]
    for i in range(1, count):
        parent_index = draw(st.integers(min_value=0, max_value=i - 1))
        spans.append(make_span(span_id(i), span_id(parent_index), offset=i))
    return spans


def walk(node: SpanNode) -> list[SpanNode]:
    """Every node in a subtree, iteratively — the tree may be deep."""
    seen: list[SpanNode] = []
    stack = [node]
    while stack:
        current = stack.pop()
        seen.append(current)
        stack.extend(current.children)
    return seen


def emitted(root: SpanNode | None, orphans: list[SpanNode]) -> list[str]:
    nodes: list[SpanNode] = []
    if root is not None:
        nodes.extend(walk(root))
    for orphan in orphans:
        nodes.extend(walk(orphan))
    return [n.span_id for n in nodes]


def max_depth(node: SpanNode) -> int:
    deepest = 0
    stack = [(node, 1)]
    while stack:
        current, depth = stack.pop()
        deepest = max(deepest, depth)
        stack.extend((child, depth + 1) for child in current.children)
    return deepest


class TestConservation:
    """The property the docstring promises: no span is silently dropped.

    `build_tree` says a span whose parent is absent is returned as an orphan
    "rather than dropped", because "hiding those spans would make a trace look
    complete when it is not". That promise has to hold for every input, not only
    for the absent-parent case it was written about.
    """

    @given(spans=span_graphs())
    @COMMON
    def test_every_span_appears_exactly_once(self, spans: list[Span]) -> None:
        root, orphans = build_tree(spans)
        out = emitted(root, orphans)

        expected = {s.span_id for s in spans}
        assert set(out) == expected, "spans were lost or invented"
        assert len(out) == len(expected), "a span appeared more than once"

    @given(spans=span_graphs())
    @COMMON
    def test_duplicate_span_ids_collapse_to_one_node(self, spans: list[Span]) -> None:
        """Two rows can share a span id.

        The spans table is keyed `(started_at, span_id)` because Timescale
        requires the partitioning column in every unique index — so the same
        span id arriving with a different timestamp is two rows, and both reach
        this function.
        """
        duplicated = [*spans, make_span(spans[0].span_id, spans[0].parent_span_id, offset=999)]
        root, orphans = build_tree(duplicated)
        out = emitted(root, orphans)
        assert len(out) == len(set(out))


class TestNoCycles:
    """Cycles are reachable from untrusted input.

    Span ids come from the client, so nothing prevents A naming B as its parent
    while B names A — or a span naming itself. The output must still be a tree,
    or serialising it recurses forever.
    """

    @given(spans=span_graphs())
    @COMMON
    def test_output_is_acyclic(self, spans: list[Span]) -> None:
        root, orphans = build_tree(spans)
        for start in [*([root] if root else []), *orphans]:
            seen: set[int] = set()
            stack = [start]
            while stack:
                node = stack.pop()
                assert id(node) not in seen, "the assembled tree contains a cycle"
                seen.add(id(node))
                stack.extend(node.children)

    @given(spans=span_graphs())
    @COMMON
    def test_result_is_serialisable(self, spans: list[Span]) -> None:
        """The endpoint returns this. If it cannot serialise, the trace 500s."""
        root, orphans = build_tree(spans)
        if root is not None:
            root.model_dump()
        for orphan in orphans:
            orphan.model_dump()

    def test_self_parenting_span_survives(self) -> None:
        """The minimal cycle, and the one a single off-by-one produces."""
        sid = span_id(1)
        root, orphans = build_tree([make_span(sid, sid)])
        assert emitted(root, orphans) == [sid]

    def test_two_span_cycle_survives(self) -> None:
        a, b = span_id(1), span_id(2)
        root, orphans = build_tree([make_span(a, b), make_span(b, a)])
        assert sorted(emitted(root, orphans)) == sorted([a, b])


class TestArrivalOrder:
    """Order independence, generated rather than assumed.

    Spans complete innermost-first while a batching exporter flushes on a timer,
    so the arrival order is arbitrary. The integration suite checks one
    reversed ordering; this checks every ordering Hypothesis can find.
    """

    @given(spans=well_formed_trees(), data=st.data())
    @COMMON
    def test_shuffling_input_preserves_the_parent_child_edges(
        self, spans: list[Span], data: st.DataObject
    ) -> None:
        shuffled = data.draw(st.permutations(spans))

        def edges(rows: list[Span]) -> set[tuple[str | None, str]]:
            root, orphans = build_tree(rows)
            found: set[tuple[str | None, str]] = set()
            for start in [*([root] if root else []), *orphans]:
                stack = [(None, start)]
                while stack:
                    parent_id, node = stack.pop()
                    found.add((parent_id, node.span_id))
                    stack.extend((node.span_id, c) for c in node.children)
            return found

        assert edges(spans) == edges(list(shuffled))

    @given(spans=well_formed_trees())
    @COMMON
    def test_a_well_formed_tree_has_exactly_one_root_and_no_orphans(
        self, spans: list[Span]
    ) -> None:
        root, orphans = build_tree(spans)
        assert root is not None
        assert orphans == []
        assert len(emitted(root, orphans)) == len(spans)


class TestOrphans:
    @given(spans=span_graphs())
    @COMMON
    def test_a_span_whose_parent_is_absent_is_never_inside_the_tree(
        self, spans: list[Span]
    ) -> None:
        present = {s.span_id for s in spans}
        detached = {
            s.span_id
            for s in spans
            if s.parent_span_id is not None and s.parent_span_id not in present
        }
        assume(detached)

        _, orphans = build_tree(spans)
        orphan_roots = {o.span_id for o in orphans}
        assert detached <= orphan_roots, "a span with an absent parent was hidden in the tree"


class TestDepth:
    """Pydantic's serialiser refuses to descend past 255 levels.

    A trace nested deeper than that is not exotic — a recursive agent or a
    runaway loop produces one, and the ingest API will accept it. Without a
    bound, reading that trace back returns a 500 and the whole trace becomes
    unreadable rather than merely deep.
    """

    @given(depth=st.integers(min_value=1, max_value=400))
    @COMMON
    def test_a_deep_chain_is_returned_and_serialisable(self, depth: int) -> None:
        spans = [
            make_span(span_id(i), span_id(i - 1) if i else None, offset=i) for i in range(depth)
        ]
        root, orphans = build_tree(spans)

        assert len(emitted(root, orphans)) == depth, "spans lost to depth truncation"
        assert root is not None
        assert max_depth(root) <= MAX_TREE_DEPTH
        root.model_dump()
        for orphan in orphans:
            orphan.model_dump()

    @pytest.mark.parametrize("depth", [MAX_TREE_DEPTH - 1, MAX_TREE_DEPTH, MAX_TREE_DEPTH + 1])
    def test_behaviour_at_the_boundary(self, depth: int) -> None:
        spans = [
            make_span(span_id(i), span_id(i - 1) if i else None, offset=i) for i in range(depth)
        ]
        root, orphans = build_tree(spans)
        assert len(emitted(root, orphans)) == depth
